# Generated by Django 5.1.7 on 2025-03-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0002_auto_20250317_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
    ]
