# Generated by Django 5.1.7 on 2025-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_auto_20250317_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20),
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='last_accessed',
            new_name='updated_at',
        ),
    ] 