# Generated by Django 5.1.7 on 2025-03-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_auto_20250317_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ] 