# Generated by Django 5.1.7 on 2025-03-18 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_progress_enrollment_remove_progress_completed_and_more'),
        ('enrollments', '0006_enrollment_completion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='content',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='notes',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_record', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
